### ISSUE TITLE
Cookie notice

### ISSUE THREAD

**Issue by PatrickHeneise** [blended/barcelona.nodeconf.com#11]
this is the recommendation from GoSquared. Anyone knows how to implement that?

> This website uses web analysis services provided by Go Squared Ltd. ("GoSquared").
> 
> GoSquared's services uses cookies, text files that are stored on your computer and which enable an analysis of your use of this website. The information generated by the cookie about your use of this website (including your IP address) are transmitted to GoSquared (which may use data repositories outside of the European Economic Area (EEA) such as the United States of America), where it is then stored for us.
> 
> We control how the information collected about you is used. GoSquared will use it on our behalf to evaluate your use of this website and report to us about this website's operations. GoSquared may provide it to third parties if needs be, for example, in order to comply with the law or to third parties processing that information on behalf of GoSquared. GoSquared may also use the information we provide to look up publicly-available contact and social data related to you, so as to enable us to enhance your experience of this website. For more information on GoSquared's practices and policies, please see https://www.gosquared.com/legal/
> 
> If you wish to restrict or block cookies you can do this through your browser settings - the Help function within your browser should tell you how. Alternatively, you may wish to visit www.aboutcookies.org which contains comprehensive information on how to do this on a wide variety of browsers. Please be aware that restricting cookies may impact on the functionality of this website.
> 
> By using this website, you consent to the processing of the data captured relating to your use of the website by us (and by GoSquared acting on our behalf) in the manner and for the purposes described above, as may be supplemented by our privacy policy.

**Comment by nuria-fl** [comment]
Should we create a static page or modal with this info and point to it instead of https://www.gosquared.com/legal/privacy/statement/ ? 

We should probably display the link in the footer too, so it's accessible when you've closed the cookie notice.

**Comment by PatrickHeneise** [comment]
> We are using cookies to provide statistics that help us give you the best experience of our site. You can find out more or switch them off if you prefer. However, by continuing to use the site without changing settings, you are agreeing to our use of cookies.

<img width="1327" alt="screen shot 2017-01-25 at 11 49 20" src="https://cloud.githubusercontent.com/assets/74390/22287796/76b0569a-e2f4-11e6-923f-05a9646e0b50.png">

This is from https://www.cookielaw.org/. We don't have the "turn off" button, so it would be:

`This website uses web analysis services provided by Go Squared Ltd. ("GoSquared"). By continuing to use the site, you are agreeing to our use of cookies. For more information on GoSquared's practices and policies, please see https://www.gosquared.com/legal/.`

Notice should be hidden and never show up again once accepted.

**Comment by nuria-fl** [comment]
Done
